### ISSUE TITLE
Blast index file

### ISSUE THREAD

**Issue by Sankalp83** [dstar4138/pjblast#1]
Thanks for your blast program !!!

**Comment by dstar4138** [comment]
You're welcome, most of the credit goes to @sem6252 for his work on the BLAST algorithm implementation.

I only ask that this not be submitted for homework/project credit, but rather for self-education purposes.

Have a great day!

**Comment by Sankalp83** [comment]
Thanks for your response !!!!
Will you share your and a@sem6252 email id.
So I will further communicate it !!!
